### ISSUE TITLE
组件图表展示bug

### ISSUE THREAD

**Issue by tcj98** [alibaba/lowcode-engine#2292]
## **Describe the bug (required)** / **详细描述 bug（必填）**
在官网demo-general综合场景demo中，添加容器，再进行切分，随后将任意图表拖入容器中，图表不是固定大小展示，而是一直在膨胀

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

1. 打开https://lowcode-engine.cn/demo/demo-general/index.html
2. 添加容器
3. 将容器切分成多列
4. 将任意图表拖入容器中

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
图表固定大小，不会一直在膨胀，从而能正常使用
---

## **Screenshots (optional)** / **bug 截图（可选）**
![image](https://github.com/alibaba/lowcode-engine/assets/109788621/1c0d7929-6b6b-40f1-886b-451c556f1161)
![image](https://github.com/alibaba/lowcode-engine/assets/109788621/08a5f817-29ef-4684-9c5b-9837ea3a5446)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version:  v1.1.9-beta 
 - AliLowCodeEngineExt version: v1.0.6-beta.28
 - AliLowCodeEngineDemo  version: v1.1.71
 - Browser Google Chrome Version 114.0.5735.198

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by tcj98** [comment]
这个bug已经两周了，请问有进展了吗

**Comment by tcj98** [comment]
> 这个bug已经两周了，请问有进展了吗

**Comment by Cuiyansong** [comment]
粗略的跟了下这个问题（Demo环境可以复现），大体原因如下：
1. Section容器采用了[`@alifd/layout/view.css`](https://alifd.alicdn.com/npm/@alifd/layout@2.0.12/build/lowcode/view.css)的Paragraph段落作为容器载体，容器会默认向下一级的非Text类型的节点添加margin-top/bottom。
```css
.fd-layout-p-margin>* {
    margin-top: var(--page-p-el-margin);
    margin-bottom: var(--page-p-el-margin)
}

.fd-layout-p-margin>.fd-layout-text,
.fd-layout-p-margin>text {
    margin-top: 0;
    margin-bottom: 0
}
```
2. FusionUI的chart默认使用fouceFit的方式来适应容器高度和宽度，而多加出来的margin会影响chart的监听判断。

总的来说，还是要考虑是否用Layout的Paragraph作为容器载体，或者默认修改Paragraph的css默认margin为0px（在当前物料环境下，只是载体容器而并非段落，所以强制覆盖css也不过分，只是语义化上有点歧义）
